### ISSUE TITLE
Create dedicated pages for project categories

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#100]
This is more of an epic or design project than a standalone issue, but I'm opening it for discussion and contribution, especially related to design and things I've missed.

We'd like to transform the simple "filter projects by tag"  – for Medical Equipment, Help the community, Scale testing, Track the outbreak, Communications, etc – into more dedicated-looking pages where we can:

a) explain what this category does and is for
b) highlight projects in that specific category, independent of the general homepage highlighting

This is similar to Kickstarter's category pages, e.g. http://kickstarter.com/arts vs. http://kickstarter.com/film vs. http://kickstarter.com/games

For the first part, @caseypugh has started a doc w/ draft descriptions of each category: https://docs.google.com/spreadsheets/d/1p6oR087N8dUJj3pTmt0zqpg54nCSnbv2Nxp8pgTBq28/edit#gid=0

Should we also include images for each category?

On an engineering level we could do this by simply mapping URLs better and using the current tag system, or by introducing a whole new Category and ProjectCategories system? Former seems much simpler.

We could also then start to think about subcategories

**Comment by caseypugh** [comment]
We should start picking this up as the next project.   @cat-liu @tinnei do you have designs or WIP designs for this?

**Comment by cat-liu** [comment]
@caseypugh yes, we have started wireframing how the category pages/all category page will look. Still in wireframing, but plan to review and start pushing forward for next steps,
