### ISSUE TITLE
Add tweet length description field

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#109]
Hi all! We'll need to add a **"Short description"** field to the project page. The character limit should be 129 chars. (😬 cc: @caseypugh @jamiew )

This is for our new project card design - easier for users to read on home page! 

<img width="698" alt="Screen Shot 2020-04-01 at 9 53 52 PM" src="https://user-images.githubusercontent.com/9310999/78211953-4ebfd300-7463-11ea-871b-49e73e7c0444.png">

**Comment by caseypugh** [comment]
Just wanted to note that on the project form, let's phrase this display this field as:
`Describe your project in a Tweet:`

**Comment by bansalnagesh** [comment]
Please assign this to me. 
Just a quick question, for existing projects, do we want to truncate to 129 characters from their long description by default, which they can edit later on or do we want to keep it as blank?

**Comment by caseypugh** [comment]
@bansalnagesh No, that's ok. Would like to know which projects have & havent filled it out. We can just choose to display a truncated description if the the tweet version doesn't exist.

**Comment by caseypugh** [comment]
I'm reopening this because we need to actually implement them into the new Project Card designs. If tweet lenght exists, use that. Otherwise fallback to old description.

**Comment by vanillafrosty** [comment]
@caseypugh I tried to open a PR for this, but I got a 403 error:
`remote: Permission to helpwithcovid/covid-volunteers.git denied to vanillafrosty.`

Any ideas on how I can get permissions to create and push to a branch, as well as create a PR?

**Comment by sradu** [comment]
@vanillafrosty fork and do a PR!

**Comment by vanillafrosty** [comment]
@caseypugh @sradu Can we close this one out?

**Comment by sradu** [comment]
Yup
