### ISSUE TITLE
Escape user input

### ISSUE THREAD

**Issue by jmstfv** [helpwithcovid/covid-volunteers#115]
I managed to sneak a link to my website by inserting the anchor tag into the input field. You're not escaping the user input, and that's ripe for abuse by spammers.

You're  [using simple_format](https://github.com/helpwithcovid/covid-volunteers/blob/master/app/views/offers/show.html.erb#L51), which sanitizes the input but doesn't escape it.

Quoting [Rails docs](https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html):

> Most text helpers that generate HTML output sanitize the given input by default, but do not escape it. This means HTML tags will appear in the page but all malicious code will be removed. Let's look at some examples using the simple_format method:

> If you want to escape all content, you should invoke the h method before calling the text helper.

To escape the input:

```
<%= simple_format h(@offer.description), class: 'mb-3' %>
```

Here's [the page](https://helpwithcovid.com/offers/37) in question (hover over the URL in the description section, and you'll notice that it is clickable). Also, formatting for this item looks off when looking from [the index page](https://helpwithcovid.com/offers).

Would you be open for the pull request?

**Comment by jamiew** [comment]
@jmstfv would happily accept a pull request for this (and any other spots we might not be sanitizing). Bonus points for tests. Thanks!

**Comment by sradu** [comment]
From the channel:

I think it was intentionally done like that if simple_format was added to that section - if you are offering something for volunteers and projects dealing with COVID-19 a link back is not a big deal.

Outside of linking back, genuinely asking, is there any other attack vector?

**Comment by jamiew** [comment]
I'd have to test this, but if we're not sanitizing HTML, couldn't you inject a <script> or a malicious <img> tag?

**Comment by sradu** [comment]
Seems to sanitize by default according to: https://apidock.com/rails/ActionView/Helpers/TextHelper/simple_format. Perhaps try it out?

**Comment by jmstfv** [comment]
> I think it was intentionally done like that if simple_format was added to that section - if you are offering something for volunteers and projects dealing with COVID-19 a link back is not a big deal.

There are two problems with that.

First, this _feature_ is neither undocumented nor intuitive. I had to insert the anchor tag to make this work. Most posters won't be able or won't bother figuring this out.

Also, posts in that section are not vetted by anyone last time I checked. That's a spam magnet.

**Comment by jmstfv** [comment]
> If we're not sanitizing HTML, couldn't you inject a <script> or a malicious <img> tag? I don't recall the specifics of simple_format and the latest with html_safe etc offhand

With `simple_form`, the input is _sanitized_, but not _escaped_. It is safe against JavaScript injections.

**Comment by sradu** [comment]
I'm definitely open to changing this if it becomes a SPAM magnet, it's been OK until now. For the resources page (offers_controller) I'd prefer if we go the other route and add auto_link.

**Comment by jamiew** [comment]
I'm going to mark this one as #willnotfix since we haven't run into issues. I've also filed #162 which would further deter spam

Thanks for flagging @jmstfv!
