### ISSUE TITLE
Add Project Name & Role Tags to Volunteer Pop-up

### ISSUE THREAD

**Issue by cat-liu** [helpwithcovid/covid-volunteers#119]
Before:
![image](https://user-images.githubusercontent.com/20099770/78630072-9c668200-784d-11ea-80ab-f4ef46573c48.png)

After (just the content, don't follow the mock-up design):
- [ ] Add project name that volunteer is volunteering for
- [ ] Add 'skill-needed' tags
![image](https://user-images.githubusercontent.com/20099770/78630110-b738f680-784d-11ea-8b9b-c046fe4dfc32.png)

**Comment by bansalnagesh** [comment]
Please assign this to me.
