### ISSUE TITLE
[Home page] Add see more to featured project row

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#122]
- [ ] Add "See more featured projects" arrow link
- [ ] Link to page with highlighted projects filtered

Figma link here: [[TASK] Home - Featured project row update](https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=503%3A2 )

<img width="820" alt="Screen Shot 2020-04-07 at 10 52 16 PM" src="https://user-images.githubusercontent.com/9310999/78749120-765ee180-7922-11ea-9095-e55e07f5dd2f.png">

Need @cat.liu's approval!

**Comment by caseypugh** [comment]
ill pick this one up
