### ISSUE TITLE
Add "Upcoming events" to resources page 

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#132]
**Please add the following upcoming events to resource page 🙏**

**Header:** Project Owners Office Hours led by Jamie Wilkinson
**Sub-header:** Thursday, April 9th 4pm-5pm PST | [Complete Office Hours Questionnaire ](https://docs.google.com/spreadsheets/d/1TBW8F29202kdKs8kclI-3SZHJMZ6QjYW0l0UfIyFnKc/edit#gid=0)
**CTA:** [Click here to add to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjY0cnBkazRkZWJobm1qYmxuanNxbWU5ZmQgbWlzYUBvcGVuYWkuY29t&tmsrc=misa%40openai.com)

**Header:** Project Owners Office Hours led by Jeeshan Chowdhury
**Sub-header:** Friday, April 10th 12pm-1pm PST | [Complete Office Hours Questionnaire](https://docs.google.com/spreadsheets/d/1_hKpejkq1Kf2Hs3dCTbcdJnHPx7LCLWDCIJec4PswJM/edit#gid=0)
**CTA:** [Click here to add to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=MWo2ajM3ZHV0ZGRwZmVjZnJrM3Y3MnFtZmEgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com)

**Header:** Project Owners Office Hours led by Radu Spineanu
**Sub-header:** Tuesday, April 14th 4pm-5pm PST | [Complete Office Hours Questionnaire](https://docs.google.com/spreadsheets/d/1z8jJdeHssfCSbsQ9HrmBebOdM1jCLk8nux7tJIUDCHY/edit#gid=0)
**CTA:** [Click here to add to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjE4MXNhYWQ1ZmRyMDcwbWc1ZHJjZ3ZsdGsgbWlzYUBvcGVuYWkuY29t&tmsrc=misa%40openai.com)

**Header:** Live Webinar with Ambika Bumb 
**Sub-header:** Thursday, April 16th 12pm-12:30pm PST | Ambika is a Health, Science and Technology Advisor focusing on Crisis Management and Strategy. 
**CTA:** [Click here to add to your calendar.](https://calendar.google.com/event?action=TEMPLATE&tmeid=NDZ0bGNzOG9rbDN0NWpkbHV0cm5zOHRqOTQgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com)

**Quick design mock**
Here's a quick mock for how the new "Upcoming events" module fit into current resources screen (for now). Let's use the same resource module style in home page.
<img width="742" alt="Screen Shot 2020-04-08 at 11 05 40 AM" src="https://user-images.githubusercontent.com/9310999/78818074-f029b600-7988-11ea-8762-dc375fb66b04.png">

**Comment by adrianthedev** [comment]
Are these events different from the ones on the homepage footer?
