### ISSUE TITLE
[Create a Project] UPD location field to country dropdown

### ISSUE THREAD

**Issue by cat-liu** [helpwithcovid/covid-volunteers#134]
UPD this field in “create a project” to either a country drop down or a search-and-select based off of where the project originated. 

Q: Potentially expand this issue to allowing users to filter projects by country. 

![011002F9-0BDF-41AB-BEBC-2A7E6C68403B](https://user-images.githubusercontent.com/20099770/78822925-b8267100-7990-11ea-881c-49090fb28139.jpeg)

**Comment by caseypugh** [comment]
is this different than what just went live? or can we close this? 

![image](https://user-images.githubusercontent.com/156097/78948055-28b6b600-7a95-11ea-97c3-dbbd16598a05.png)

**Comment by cat-liu** [comment]
Looks like we can close!
