### ISSUE TITLE
Duplicate projects on index page?

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#137]
Currently, I'm seeing the same project on each category, eg: "COVID 19 - Idea Sprint" showed up 3 times.

Is there a way to exclude projects that are already on other rows?

<img width="689" alt="Screen Shot 2020-04-09 at 1 46 20 PM" src="https://user-images.githubusercontent.com/9310999/78939209-8ed91400-7a68-11ea-9b64-7225f4d2d7ba.png">

**Comment by caseypugh** [comment]
This should be fairly easy to fix. Will take a stab at it.

**Comment by adrianthedev** [comment]
Wouldn't it be a good idea to randomize those too?

**Comment by caseypugh** [comment]
@adrianthedev oh yea, good idea. for some reason I just assumed it was randomized already.
