### ISSUE TITLE
Refine layout and spacing in Project Card component

### ISSUE THREAD

**Issue by colin-johnston** [helpwithcovid/covid-volunteers#145]
The Project Card component feels bulky and would benefit from adjustments to relative size and spacing of internal elements. 

Ideally, this should be done before the card is rendered many times on category pages and filtered views.

![image](https://user-images.githubusercontent.com/1129103/79013496-bc33c980-7b1d-11ea-8e27-3f4ef64cbd5a.png)

Self-assigning to make changes directly to Tailwind CSS styles in a ~~feature~~ fix branch.

**Comment by colin-johnston** [comment]
I don't have privileges to edit issue metadata. 

I'd suggest: 

- assignee: me
- labels: ux/ui, enhancements, fit-and-finish (new label request)
- projects: roadmap

**Comment by colin-johnston** [comment]
@cat-liu In progress - see PR (I'm not able to move on project board)

**Comment by cat-liu** [comment]
@colin-johnston please see attached file of ISO countries. 

[ISO Countries.txt](https://github.com/helpwithcovid/covid-volunteers/files/4473320/ISO.Countries.txt)
