### ISSUE TITLE
Nav with many menu items breaks branding component

### ISSUE THREAD

**Issue by colin-johnston** [helpwithcovid/covid-volunteers#146]
After creating an account locally I noticed the nav header was breaking:

![image](https://user-images.githubusercontent.com/1129103/79016498-0324bd80-7b24-11ea-8d8a-57aa302e8868.png)

Besides the component issue, I suggest that 8 menu items is not ideal from a usability perspective.

To solve quickly, I suggest we have user-specific dropdown next to Create Project button that contains options in user context:

**{menu-item label TBD}**
- Your Projects
- Profile
- Log Out

**Comment by cat-liu** [comment]
I agree with this suggestion. “Volunteered Projects” should also live under “Your Profile”. 

How would double collapse work on mobile?

**Comment by tinnei** [comment]
Sounds good to me! Looks like with this update, the menu bar will be:

```
1 Find projects, 
2 Volunteers, 
3 Resources, 
4 Discord, 
5 Your profile
-- Volunteered projects
-- Log out
```

For mobile, we can have all menu items pan out. Maybe indent the sub-menu.

**Comment by cat-liu** [comment]
@tinnei 

“Your projects” should also live under your profile? 

1 Find projects, 
2 Volunteers, 
3 Resources, 
4 Discord, 
5 Your profile
-- Volunteered projects
_— Your projects_
-- Log out

**Comment by colin-johnston** [comment]
We need to provide users a way to get to their Profile page as well.

**Comment by tinnei** [comment]
Design update from Colin here - 
<img width="944" alt="Screen Shot 2020-04-20 at 9 13 59 PM" src="https://user-images.githubusercontent.com/9310999/79824768-e66e5e00-834b-11ea-8206-b842c98d54c4.png">

https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=864%3A67

**Comment by colin-johnston** [comment]
@tinnei Thanks for formalizing the presentation here so nicely! 🙌🏻 Very much appreciated.

**Comment by adrianthedev** [comment]
Looks good! I'll pick it today.
