### ISSUE TITLE
Volunteer skillset add and required field

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#149]
Please make volunteers skillset a required field on volunteer profile page.

Please add following skillset:

1) Helpdesk
2) Community Outreach
3) Training Development
4) Legal
5) QA
6) Sales

**Comment by shen-sat** [comment]
Hi I can pick this up :)

Would it be too much if I wrote a feature spec for this? I was thinking of testing two scenarios:
1) Skill set selected and form submitted
2) Skill set not selected and form submitted

**Comment by caseypugh** [comment]
@shen-sat specs are most appreciated!
