### ISSUE TITLE
Location is overflowing on project card

### ISSUE THREAD

**Issue by cat-liu** [helpwithcovid/covid-volunteers#153]
Looking a little funky @caseypugh @jamiew @sradu . I think we need to remove the input location soon?

![image](https://user-images.githubusercontent.com/20099770/79059828-44f05980-7c33-11ea-88b4-61d925e131ca.png)

**Comment by caseypugh** [comment]
Don't we have three location based fields now? We added those new ones the project card wasn't discussed on how it should be updated after making those changes.

![image](https://user-images.githubusercontent.com/156097/79149142-b1cf3500-7d94-11ea-869f-a4eb32f93960.png)

Probably should use `Target Country` instead? Or leave as `Volunteer location` and simply truncate the text if it goes multiline.

**Comment by cat-liu** [comment]
@caseypugh 
For project card, I would imagine it would only show Target Country (search and select). Anything other user-inputted text would not fit on the card from a design standpoint. 

Even then... there are some very long country names (char. count) that I am concerned with. For instance USA is spelled out United States of America. What abbreviation integrations are available? If the country list can be provided, we can make adjustments to the design to make the country fit better on the project card.

**Comment by cat-liu** [comment]
@caseypugh +1 to using Target Country and truncating for longer country names (e.g. United States of America) or are there abbreviations tht can be used?

**Comment by colin-johnston** [comment]
Here is the live project card layout & style with a location set to the longest ISO Country name:

![Screenshot_2020-04-15 Help With COVID-19 2](https://user-images.githubusercontent.com/1129103/79388608-782c3480-7f22-11ea-8dfb-4b174ff0ff13.png)

My suggestion is to provide 2 ways to enter location, each enabled by a radio button. This way only one can be set.

- dropdown with ISO Country names
- 'Remote'

Alternately we also include a text field for entering in plain text, _limited to a specific number of characters_ (~50 for a two-line location).

Design-wise it might make sense to move the location to its own line—left-aligned above volunteers and updated elements:

![Screenshot_2020-04-15 Help With COVID-19 3](https://user-images.githubusercontent.com/1129103/79389971-bc6c0480-7f23-11ea-8efd-32f5862f4c8f.png)

I have the above layout stashed in my old `fix/project-card-styles` branch so I could do a quick PR...

**Comment by cat-liu** [comment]
@tinnei feel free to jump in on comments for the above project cards^

I like #1, but is there a way to make the "day" - element stick on its line ( e.g. 2 days ago is directly underneath volunteer number)?

re: text field char. limit -- is this comment for entering a location?

**Comment by cat-liu** [comment]
@caseypugh to answer your question, the card should have a restricted version of the location. Target Country would be the best field for this as we can design around the worst case.

**Comment by tinnei** [comment]
Re which field to show: +1 on showing "Target country" in this project preview card.

Re design: I don't think we should do location in a separate line just to compensate for a long country name, because it'll look really empty with short country names (most cases). I'd suggest having chat limited to location length, eg: if more then 30 chars, we do "...".

**Comment by colin-johnston** [comment]
@cat-liu @tinnei what is status of this? If we are going to limit the chars of location so it fits without wrapping ,we don't need to change the current layout and CSS (#1).

**Comment by colin-johnston** [comment]
We should put full location text in a title tag so users can reveal the full text that's truncated.

**Comment by cat-liu** [comment]
@colin-johnston I think it is still there, has anyone worked on this in dev yet?

**Comment by colin-johnston** [comment]
@cat-liu Thanks for following up on this and bumping it back up in my queue. I need to make a small change in card template to accommodate long country entries, then this will be 100% done.

The change will keep the time-ago piece directly underneath the volunteer number.

![image](https://user-images.githubusercontent.com/1129103/80160486-9cbb8880-8582-11ea-8fb7-f2aad93145f1.png)
