### ISSUE TITLE
HWC - About Page

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#157]
Please add:

Ambika Bumb : https://www.linkedin.com/in/ambikabumb/ 

bansalnagesh (developer)

**Comment by sradu** [comment]
I need more info for @bansalnagesh!

**Comment by sradu** [comment]
@bansalnagesh also can you please make a PR

**Comment by sradu** [comment]
Will push change for Ambika. @bansalnagesh can do a PR that closes this issue!

**Comment by bansalnagesh** [comment]
Will do today
