### ISSUE TITLE
Update project detail page

### ISSUE THREAD

**Issue by caseypugh** [helpwithcovid/covid-volunteers#161]
The existing [project page](https://helpwithcovid.com/projects/262-remote-detection-of-vital-signs-respiration-hr-hrv-for-remote-symptoms-analysis-and-tracking) is very hard to digest. Needs better information hierarchy and general ui/ux love. Also needs to include the upcoming project images (#111)

### Update: Designs finished!
Here is the Figma link https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=414%3A2306
![unknown](https://user-images.githubusercontent.com/156097/79470504-7b312e80-7fcf-11ea-89e5-df7aca9659f5.png)

awesome work @tinnei @cat-liu @colin-johnston !

**Comment by ryanhefner** [comment]
@caseypugh Yo! I have some ideas for this one. Feel free to assign it to me and I can get a first pass up for it later today.

**Comment by caseypugh** [comment]
@ryanhefner hey man! how are you?? 

we actually have some incoming designs thanks to @tinnei @cat-liu @colin-johnston - if you want to help build them, that'd be great. we could use the help

**Comment by caseypugh** [comment]
FYI, updated task with designs & [figma link](https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=414%3A2306)

**Comment by ryanhefner** [comment]
Rad! Didn't realize you had designers on it. Yeah, I would be down to help build it out.

**Comment by caseypugh** [comment]
@ryanhefner that's great! are you in the discord? could join our product group to collab

**Comment by ryanhefner** [comment]
@caseypugh Yeah, in the Discord. Which one is the product group channel?

**Comment by caseypugh** [comment]
@ryanhefner - we're in the #admin channels (#admin-product specifically).  Any chance you can work on this today or tomorrow?

**Comment by sradu** [comment]
@ryanhefner awesome!! 

There is some discussion on discord, I believe we need to add some elements for the top menu bar and the amazing design team is on it.

also:
* the images PR was merged so we should support that model too
* we should extract the url redirect from demo or interesting links

**Comment by cat-liu** [comment]
@ryanhefner please see below for default image request:

**[Figma Link:](https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=996%3A7372)** 
![image](https://user-images.githubusercontent.com/20099770/80174903-ed45dc80-85a8-11ea-8c57-f51f10c184b8.png)
