### ISSUE TITLE
Need unique titles for category filter URLs

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#170]
Currently pages like this are showing up in Google search:

https://helpwithcovid.com/projects?highlight=true

https://helpwithcovid.com/projects?highlight=true&skills=Content

https://helpwithcovid.com/projects?project_types=Medical+equipments

But they all have the same page titles:

```
    <title>All Projects |  Help With COVID 19 - a clearing house for projects and volunteers that want to help with the COVID-19 crisis.</title>
```

Ideally we'd also be adding clean URLs for these (???) but updating titles in the meantime would make a big difference

**Comment by tiegz** [comment]
I think I have a fix for this, comin' up in a bit!

**Comment by sradu** [comment]
Friendly heads up, the new category page that is almost ready has a fix for this. cc @adrianthedev

**Comment by tiegz** [comment]
@sradu just to confirm, is the fix in that PR to pull the project type into the path, e.g. `/projects/Medical`, but the rest of the querystring would remain in the path?

**Comment by sradu** [comment]
Yes,  see the description about the PR here: https://github.com/helpwithcovid/covid-volunteers/pull/167

Dunno is this covers all cases mentioned here, I just want to make sure we're all synced up.

**Comment by jamiew** [comment]
Ah yes should've specified this is for the new categories PR, which has this same issue. URLs are like `/medical` and some have query strings, but all have same title

**Comment by tiegz** [comment]
Cool cool, here's a proposed fix: https://github.com/helpwithcovid/covid-volunteers/pull/171

**Comment by adrianthedev** [comment]
I confirm that the category urls will be like `/medical`, `/prevention` , etc.
