### ISSUE TITLE
Resources page upgrade

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#172]
Mockup:
https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=685%3A5709

<img width="1081" alt="Screen Shot 2020-04-15 at 8 39 30 PM" src="https://user-images.githubusercontent.com/1903/79402225-3e2a5500-7f59-11ea-97e5-e78ef5ef5054.png">

Some functional changes

- try to automatically hide events that have passed
- sort deals alphabetically rather than by `created_at`
- add ability to mark some deals as "partnerships" and sort to top

Questions

- should we just store Events in the database so anyone can edit?
- could we change URL to `/resources` and make `/offers` a redirect? This name seems to be in the lead for what to call this

Suggestions or questions welcome

**Comment by abhijeetgurle** [comment]
Hey, I would like to help. As I am new to open source contributions, can you get me up to speed by telling me how to contribute to this project ?

**Comment by abhijeetgurle** [comment]
Hi @jamiew, Can you assign this issue to me?

**Comment by sradu** [comment]
Tackling it via #186. @abhijeetgurle next time just work on it - ping us on Discourse. We were looking for people to help build this.

**Comment by sradu** [comment]
That design is outdated though

**Comment by sradu** [comment]
Can someone please help me with the links for these?

<img width="1076" alt="Screen Shot 2020-04-22 at 11 14 00 PM" src="https://user-images.githubusercontent.com/82214/80065474-07bb7f80-84ef-11ea-9083-dd76ba89ca41.png">

**Comment by caseypugh** [comment]
@sradu I can help out - what are the links for each of those? Do you have a list?

**Comment by cat-liu** [comment]
Please add Partner Logos to the bottom of the resources page:

Figma Link: https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=841%3A186

![image](https://user-images.githubusercontent.com/20099770/80173104-a73a4a00-85a3-11ea-9753-27b309fb0634.png)

**Comment by sradu** [comment]
@cat-liu @tinnei will close this in favor of a new ticket with Misa's requested changes.
