### ISSUE TITLE
Add empty states

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#192]
**Add an empty state graphic to the following pages:**
- category page (filtered results)
- your project page
- volunteered project page

Note: the graphic should be all the same; messages are different.

**Figma design link:**
https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=1025%3A7626

(As mentioned in admin-product - @ryanhefner @adrianthedev would any of you want to take on this task?)

<img width="1108" alt="Screen Shot 2020-04-23 at 6 04 34 PM" src="https://user-images.githubusercontent.com/9310999/80164085-e9a45c80-858c-11ea-944e-502e5b3e1075.png">

**Comment by cat-liu** [comment]
@tinnei really like the design :)
