### ISSUE TITLE
Sticking Capsule Fade Opacity

### ISSUE THREAD

**Issue by cat-liu** [helpwithcovid/covid-volunteers#194]
Looks like the fade is staying on the capsule tag when scrolling on the project card? 

@colin-johnston would you like to take this task? 

![31061401-2E5F-4AF6-9784-B07F8E9CCDB7](https://user-images.githubusercontent.com/20099770/80165188-c8913b00-858f-11ea-9f55-26417f1c583b.jpeg)

**Comment by colin-johnston** [comment]
@cat-liu I can't reproduce this in Chrome, Safari, Edge, or Firefox (all latest) on MacOS. Are you using IE Edge on a Windows machine?

Can you please visit https://mybrowser.fyi and send me the report link? Thanks!

**Comment by cat-liu** [comment]
@colin-johnston it was actually on mobile on safari. I have iphone 11, I am actually not sure about desktop, not sure how to scroll the tags. I can test it though. 

https://mybrowser.fyi/report/5ea3a1e29db8470015f82ce6
