### ISSUE TITLE
Volunteer Match - Prepare Email Text Change 

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#195]
Hi there! **(Volunteers in bcc:)**

Hope you are all doing well! Thank you for all that you are doing to work on a solution for our world and being part of helpwithcovid.com.

This project needs your help: **[Project Name]** (**Project URL**) **by project owner - [project owner email address]**. I thought you might be able to help. I have included the project owner to this email should have any questions.

If you are already on an existing project, please login to helpwithcovid.com and remove the setting "pair me with a project" from **[My Profile page](https://helpwithcovid.com/users/edit)**.  

If you feel that you are not the right fit after speaking with the project owner, please go to the **[project link above](Project URL)** and “cancel volunteer offer”.  Will work on matching you to another project. 

Please let me know if you have any questions or concerns.

Thank you!
HWC Core team

**Comment by caseypugh** [comment]
This is good to go in #211 - FYI I made a couple minor copy changes/grammar fixes.

**Comment by sradu** [comment]
@prophesy604 what do you mean by "cancel volunteer offer"? we have no such feature.

**Comment by prophesy604** [comment]
![image](https://user-images.githubusercontent.com/2389662/80646669-2794fb00-8a3b-11ea-82b2-be27a1dbfbcd.png)
@sradu
