### ISSUE TITLE
Help projects raise money

### ISSUE THREAD

**Issue by xdamman** [helpwithcovid/covid-volunteers#2]
Some projects need funding.

From rspineanu on Discord 
> We've been thinking of popping up a button that says 'Apply for funding' once projects have N volunteers (N undecided). That application could go to multiple parties.

**Step 1** could be to simply add a field asking for funding needs (if any) so that we record the information and we can surface it.

<img width="1038" alt="Screenshot 2020-03-18 at 02 13 23" src="https://user-images.githubusercontent.com/74358/76915706-8739ab80-68be-11ea-8dfc-90ccfbb1d85d.png">

Can someone add that? (sorry my skills are nodejs/postgres, not familiar with Ruby enough)

**Step 2** we could vet together the best projects and actually help them raise the money they need (e.g. by submitting a curated list to potential funders). 

Notes:
- We would have to come up with a process to vet the projects. Maybe it starts with a simple weekly newsletter to highlight those? But it would also be good to have a working group on fundraising that can be much more proactive and help the projects that need it the most.
- If the project doesn't have a legal entity, we can find a fiscal sponsor for them or create our own ("OpenCOVID"?) to enable them to receive money (that's what we did for the open source community with the [Open Source Collective](https://oscollective.org)). This has the extra benefit of making sure that those projects will have transparent finance ([example](https://opencollective.com/babel)). Happy to help here.

**Comment by sradu** [comment]
@adrianthedev was awesome enough to build it, but I'd like more people say they really want this before I approve it.

There's a popup that appears if projects have more than 50 volunteers, redirecting them to apply to Covid19-response where they can be vetted.

**Comment by jamiew** [comment]
Wdyt of lowering that threshold to ~5 volunteers and then closing this out? I think financing is great but out of current scope 

Maybe list fundraising opportunities alongside Offers/Deals?

**Comment by jamiew** [comment]
Closing out this specific issue but open to idea down the road if it makes sense. Please bump if so
