### ISSUE TITLE
[Resources Page] Add Partnerships Section

### ISSUE THREAD

**Issue by cat-liu** [helpwithcovid/covid-volunteers#207]
_Updated: 4/28/2020_

Please add the following partnerships section to the resources page after funding links and before deals:

![image](https://user-images.githubusercontent.com/20099770/80560045-67ed6e00-8994-11ea-9aad-3811052e6e6f.png)
[Figma Link for Design](https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=1117%3A11909)

- [ ] Add Partnerships Logos
- [ ] Create and Add Partnerships Resource Cards (Left to Right, then Top to Bottom)
- [ ] Update Resources Menu Nav 
![image](https://user-images.githubusercontent.com/20099770/80560310-4a6cd400-8995-11ea-9c11-4cf3d8e14cb1.png)

### Text for Partnership Deals
**AWS**

_Text for Deal:_
AWS $10,000 in AWS credits for approved projects. Your project must be a corporate entity.

_AWS "Apply Here" Link:_ helpwithcovid@gmail.com

---

**ClozeLoop**

_Text for Deal:_
Complete Sales Effectiveness Assessments for three companies we choose.  The Sales Effectiveness Assessment is an evaluation of your company’s sales Strategy, Systems, Staff and Skills aligned with short and long-term revenue goals. The assessment provides a prioritized high-impact roadmap, and clear recommendations for growth.  
$2500 value.

_ClozeLoop "Apply Here" Link:_ https://clozeloop.typeform.com/to/ccPwVe

---

**Turtle Dev**

_Text for Deal:_
40 hours of freelance engineering help is available for three companies chosen by the Turtle team. Turtle's developer network is currently specialized to React, React Native, iOS and Android. Based on your project specs and requirements, Turtle will match you with a highly qualified freelance engineer and you'll have full access to the Turtle platform to work together and manage your project. A one hour complimentary product planning session with Turtle's founders will also be available to you. 

_Turtle Dev "Apply Here" Link:_ https://forms.gle/8UaPv6Qjaw8sFBNy9

---

**Team Blind**

_Text for Deal:_
We are offering promotion at no cost for 4 projects 
Support 3 projects with native advertising 
Support 1 project with sponsored AMA post 

_Team Blind "Apply Here" Link:_ https://bit.ly/helpwithcovid_blind

**Comment by bansalnagesh** [comment]
Please assign this to me.

**Comment by cat-liu** [comment]
Thank you @bansalnagesh for picking this one up!

**Comment by bansalnagesh** [comment]
@cat-liu I don't see the partnership section in the mobile design. 
Is it supposed to be hidden on mobile?

**Comment by cat-liu** [comment]
@bansalnagesh no it is not supposed to be hidden. Finished a bit late last night, will take a look at mobile later today.

**Comment by sradu** [comment]
@bansalnagesh friendly heads up this is really urgent.

**Comment by cat-liu** [comment]
@bansalnagesh @sradu updated request above with... 

1) Mobile Design for Partnerships Section
2) Text + Link for ClozeLoop and Turtle Dev (please load in the same order - AWS, ClozeLoop, Turtle Dev, Team Blind). Cards go from Left to Right, Top to Bottom
3) Update Menu Nav on Resources page to jump to Partnerships Section

**Comment by bansalnagesh** [comment]
Will be working on this today
