### ISSUE TITLE
[Resource + Project Detail] Small updates

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#212]
1) Add the following to "upcoming event":
Event name: Group Office Hours with Radu 
Date: May 6th 
Time: 3:30pm-4:30pm PST. 
CTA: [Click here to add to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=NWZvanJyZzYybGM2dmhodmc1YmdsNmRpZWcgb3BlbmFpLmNvbV9wOW5mZ2MyZjltcnJkaGE1OW52M2tjYnNya0Bn&tmsrc=openai.com_p9nfgc2f9mrrdha59nv3kcbsrk%40group.calendar.google.com)

2) If a project hasn't filled out "Organization status", we should display a default message: "Not specified" (with the light purple).
<img width="313" alt="Screen Shot 2020-04-28 at 5 07 30 PM" src="https://user-images.githubusercontent.com/9310999/80549696-c9044a00-8972-11ea-815a-de705436fe11.png">

**Comment by bansalnagesh** [comment]
I am working on this.
