### ISSUE TITLE
[Volunteer Index Page] Design Update

### ISSUE THREAD

**Issue by colin-johnston** [helpwithcovid/covid-volunteers#220]
We've created a Volunteer card component and built a new Volunteer index view around it.

Figma: https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=1209%3A9622

Icon assets are available for export in the Figma file.

New requirement: please wrap all 'interesting links' entries in anchor tags so they're clickable.

Please ping @colin-johnston with implementation questions.

### Previews

**Card component** 
<img width="399" alt="Volunteer Card Component v2" src="https://user-images.githubusercontent.com/1129103/80999396-76ef7880-8df9-11ea-9a6c-cc06802ccf3f.png">

**Desktop view**
<img width="1200" alt="Volunteer Index - Desktop (1200w)" src="https://user-images.githubusercontent.com/1129103/80999400-7a82ff80-8df9-11ea-8075-62f0838e25a1.png">

**Mobile view**
<img width="375" alt="Volunteer Index - Mobile (375w)" src="https://user-images.githubusercontent.com/1129103/80999404-7ce55980-8df9-11ea-8be2-7300d0932070.png">

**Comment by sradu** [comment]
@adrianthedev when you have time do you think you could look into this?

**Comment by adrianthedev** [comment]
Yes. I make time this week.
