### ISSUE TITLE
[New page] Success stories

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#227]
Hi! Design for success story page is ready here.

Here are the things to add:
1) A new success story page
2) Add "Success stories" to header menu
3) For each blog post, create a separate page with title in the url

Figma link: https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=1212%3A11467

Tag me in #hwc-com-development if there're any questions!
![image](https://user-images.githubusercontent.com/9310999/81245774-bc16d480-8fca-11ea-9807-e36c01f614e9.png)

**Comment by tinnei** [comment]
@adrianthedev fyi we have 11 stories in total - let me know when you get to this ticket. I'll send you the full doc over Discord!

**Comment by adrianthedev** [comment]
@tinnei picking it up now. Please post the doc here.

**Comment by adrianthedev** [comment]
@tinnei actually that's not necessary. I'll make it editable so you, or any other admin can update those.
