### ISSUE TITLE
Skill should not be the trigger for "Volunteer filled" 

### ISSUE THREAD

**Issue by tinnei** [helpwithcovid/covid-volunteers#228]
Resurfacing the issue filed by Prophesy here --
https://github.com/helpwithcovid/covid-volunteers/issues/222

We found that if a volunteer's skill is not matching with "skills needed" in a project, the "apply to volunteer" button changes to "volunteer is filled". This shouldn't be the case.

Correct UX:
- If a volunteer's skill is not matching with "skills needed" in a project,
- he/she will still see "apply to volunteer"
- when he/she click on "apply to volunteer", a modal that alerts "you don't have matching skill" should pop-up (see below, It's in the code already)
![image](https://user-images.githubusercontent.com/9310999/81269634-71af4b00-8ffe-11ea-97ab-41f1ca937efd.png)

Let us know if this is not clear by tagging @tinnei/ @prophesy at #hwc-development! Thank you 🙏

(cc: @shen-sat tagging you since you replied to the #222 issue)

**Comment by shen-sat** [comment]
Makes sense! I'll start work on this now, thanks for the heads up @tinnei 👍
