### ISSUE TITLE
Integrate Bitly for lengthy links

### ISSUE THREAD

**Issue by bansalnagesh** [helpwithcovid/covid-volunteers#231]
![image](https://user-images.githubusercontent.com/496330/81944159-fbbc6c80-9619-11ea-8544-83114cb97889.png)

For links that are lengthy and breaking the design, integrate bitly and shorten them

**Comment by bansalnagesh** [comment]
Example Project
https://helpwithcovid.com/projects/784-raise-a-million-for-unemployed-mothers-on-mother-s-day

**Comment by sradu** [comment]
I don't like that we have to pay for bit.ly. How about we try another approach and if the link is super big we should only the domain part? eg http://docs.google.com/... instead of that long google docs strirng.

**Comment by bansalnagesh** [comment]
![image](https://user-images.githubusercontent.com/496330/82018891-cf4d3280-96a3-11ea-97ed-0f3ca71e556a.png)
