### ISSUE TITLE
Volunteer Office Hours - Selecting time error

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#235]
![image](https://user-images.githubusercontent.com/2389662/81978836-14b52580-95fa-11ea-90f0-b72061ff334a.png)

I'm logged in.

I get this error. my profile is filled out

![image](https://user-images.githubusercontent.com/2389662/81979062-65c51980-95fa-11ea-8b2e-75ca778ec2f3.png)

**Comment by sradu** [comment]
Fixed
