### ISSUE TITLE
Add Links to HWC media kit/logos to the footer

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#248]
https://helpwithcovid.com/HWC-media-kit-badges.zip
https://helpwithcovid.com/HWC-media-kit-logos.zip

**Comment by tinnei** [comment]
Design for media kit is here -- https://www.figma.com/file/7PSJtPUtwrdPRtXbtQFRFZ/helpwithcovid.com?node-id=1212%3A10628
