### ISSUE TITLE
HWBE - Footer links 

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#265]
Please update the github link to go to the HWBE repo

Please remove media kit or update media kit for HWBE

**Comment by jamiew** [comment]
This is fixed in 9b54d574fa937d3340d3f703b3b3bda2eb33b259

**Comment by jamiew** [comment]
<img width="642" alt="Screen Shot 2020-07-21 at 4 29 13 PM" src="https://user-images.githubusercontent.com/1903/88104614-b152f100-cb70-11ea-965d-bd121637175e.png">
