### ISSUE TITLE
Create /about page

### ISSUE THREAD

**Issue by mainiak** [helpwithcovid/covid-volunteers#64]
Hello.

I think it would be great if you could create about page with info about this project,
the team behind it, how you are handling login data, etc.

maybe even FAQ and link to github/twitter/etc

With only application itself and Discord server only it doesn't look "legit" enough ... despite I understand that functionality was primary goal which was more needed in crisis that nice PR.

**Comment by jamiew** [comment]
Thanks, this is a great suggestion. Project is brand-new and all-volunteers so this just hasn't happened yet

**Comment by sradu** [comment]
This was done!
