### ISSUE TITLE
Can't select text inside projects on the homepage

### ISSUE THREAD

**Issue by tog22** [helpwithcovid/covid-volunteers#67]
Can we make text inside projects on the home page selectable? I've found myself wanting to copy and paste it, but it's set up so you can only click it. 

(I am a web developer, so can help if that's helpful.)

**Comment by jamiew** [comment]
Thanks for the PR, I'll check it out momentarly! I just renamed the title and added some labels here too

**Comment by wilsonw926** [comment]
fixed with PR #71

**Comment by tog22** [comment]
Awesome 👍 🏅
