### ISSUE TITLE
Social media/portfolio field links - Volunteer form

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#74]
Request by Colin Curtin - WeTrace Project:

"hey could you add a field for linkedin/portfolio/social media onto the volunteer form?"

**Comment by sradu** [comment]
We already have "interesting links" in the profile form. The help suggestion says:
"For instance your arxiv, github, linked, twitter, or youtube. One per line."

**Comment by sradu** [comment]
Closing this since it already exists! @prophesy604 feel free to reopen again if we need to revisit, or feel free to suggest new wording.
