### ISSUE TITLE
Add new entry to Deals

### ISSUE THREAD

**Issue by prophesy604** [helpwithcovid/covid-volunteers#79]
please add in deals: https://www.humanapi.co/covid-19-response

**Comment by jamiew** [comment]
@sradu this has to be done via a production console right now, right? Currently you're only one with access

Happy to help reduce bus number if you want to add me wherever this is hosted

**Comment by sradu** [comment]
@jamiew anybody with a hwc account can create deals.

**Comment by jamiew** [comment]
Oh duh. @prophesy604 was there a reason you filed this? just a TODO for later?

**Comment by prophesy604** [comment]
Yes... todo later ...
