### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#81]
It is nice knowing how many people are visiting

Bonus points to setup events for:

* `start project` (e.g. equivalent to projects#new)
* `create project` (projects#create)
* `start user` (user/registrations#new)
* `create user` (user/registrations#create)
* `volunteered for project`
* I think that's it

**Comment by adrianthedev** [comment]
We need an analytics account set up to do this task.

**Comment by jamiew** [comment]
I just set one up, lemme know who wants access (send Google account) @sradu 

Tracking code:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-162054776-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-162054776-1');
</script>
```

thanks!

**Comment by sradu** [comment]
Got the invite, thanks!

**Comment by sradu** [comment]
It should be up.
