### ISSUE TITLE
Add a FAQ page

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#85]
- What is this project?
- Who is behind it? (also all volunteers)
- What kind of projects are being submitted?
- How are projects being evaluated?
- Which projects should I volunteer for?
- Who can I contact with questions?
- What is Discord?
- How do I not get completely overwhelmed by DIscord?
- Your questions here:)

@arminz from Discord is working on a v1 of the text, but we'll need to build and style a page for it

**Comment by adrianthedev** [comment]
We need the copy to get started.

**Comment by jamiew** [comment]
OK, will post again when more is written up

**Comment by jamiew** [comment]
Thanks for @arminz we've got a first version of this – will share shortly

**Comment by jamiew** [comment]
Closing unless this becomes more of a priority
