### ISSUE TITLE
Add a "country" field and dropdown menu to Projects

### ISSUE THREAD

**Issue by jamiew** [helpwithcovid/covid-volunteers#98]
Not sure if there is a canonical list of countries or country codes out there, but we'd like to ask projects for a specific country, in addition to the open-ended "Location" field that is there currently. Should be supplemented with "Global" as first option.

**Comment by lisamai** [comment]
Gave this a go based on ISO countries. I based the helper text on the Location field; not sure if that was correct. Looks like this:

Edit view
![image](https://user-images.githubusercontent.com/3603130/78105696-c3413600-73bf-11ea-99ba-ac861de2dc12.png)

Edit view with dropdown selected.
![image](https://user-images.githubusercontent.com/3603130/78105707-c9371700-73bf-11ea-8811-0b791a54e65c.png)

**Comment by caseypugh** [comment]
@lisamai that's exactly what we're looking for! The one additional change would be to make the country clickable and it'd take you to the list of projects filtered by country.

**Comment by sradu** [comment]
This is great but we need to think about it a bit more. We have a field called location that asks where volunteers should be from.

We should re-use the location for that, and perhaps build a migration script for the data, from free form to ISO select.

Perhaps also change the text to have it more encompassing: "Does this project target a certain area and wants volunteers only from there?" or something similar.

Another option is to slip it into two: volunteer location, target market. Perhaps that would be better. We still need that migration script, perhaps there are some easy to use NLP libraries out there.

**Comment by phylor** [comment]
I like the idea of the target market. 👍 I assume that people would want to help out in their local area.

I don't see the need for a migration script though. Imagine you're manufacturing something in Germany (you have the infrastructure there), but your target market is Sweden (where your product is required). We don't know whether the volunteer location is the same as the target market.

The same is true for digital products. You might build a digital product which helps out Austria, but people from all over the world may participate (location == `remote`).

My suggestion would be to keep the free text field for the location of the volunteers (either a location or `remote`). Additionally, provide the suggested select list (countries) for the **target market**.

You could then filter for the target market, which helps out bringing projects from other countries to the platform.

**Comment by sradu** [comment]
@jamiew @caseypugh looking for input here

**Comment by lisamai** [comment]
Either way is fine with me; I think making this a target market could make sense to differentiate the purposes. Besides that decision, if the country is clickable to filtering, then would we want country to also be one of the filter options at the top? Listing all the countries may be overwhelming.

**Comment by jamiew** [comment]
I'd propose:

* we add this country dropdown as a new field `projects.country` which is tied to ISO, but change the  question to say something like what @sradu proposed: "Is this project only targeting people in a specific country?" 
* keep the open-ended `location` field but change question to: "Specific state, province or city within that country?"
* migrate the existing data. Delete Global & friends, then manually clean up the rest. I'd be happy to do this part, there aren't many

Here are the `Location` values for all the current projects:

```
curl https://helpwithcovid.com/projects.json > projects.json
cat projects.json | jq '.[] .location' | egrep -i -v "(remote|global|nywhere|world)"
```
=>
https://gist.github.com/74c6c4f5dbc93bb20fe2d5ef94a9b3c6

This list has <50 projects, which is less than 10% of total projects`

I reviewed a handful manually and I believe many project creators are just putting in their own location, rather than their target market, as has been pointed out above.

I also liked the suggestion here of differentiating "where we'd like to source volunteers" and "only working with people in a specific area"

I think project creators would accept volunteers from anywhere – perhaps you're an ex-pat, perhaps you just love that country, whatever. Creators want volunteers.

With this feature we are more interested in enabling filtering down to projects that have an exclusively local impact. For instance, I would personally like to be alerted about projects that are happening where I'm from. I don't necessarily want to be alerted about all projects.

**Comment by sradu** [comment]
@jamiew because the current wording for location is: 'Do volunteers need to live in a certain location? Write remote otherwise.' we have to be careful about the migration.

The proposed idea here, which I support, would have the location field refer to target market instead of volunteers.

So one migration could be:
1) rename location to volunteer_location
2) add target_country & target_location

From a logical point of view keep the _location fields as free form.

**Comment by jamiew** [comment]
Is there a benefit to collecting and storing `volunteer_location` or is that more just to keep the existing data as-is?

**Comment by sradu** [comment]
@jamiew the latter - we can drop it if we don't need city/state.

**Comment by jamiew** [comment]
Cool that makes sense to me

Also just realized should maybe have been commenting on #105 instead... @lisamai would you be willing to implement the changes @sradu proposed in his previous comment?

**Comment by lisamai** [comment]
Yep, I should be able to get to implementing the suggested field updates in a day or so @jamiew

**Comment by lisamai** [comment]
Updated screenshots:

![image](https://user-images.githubusercontent.com/3603130/78850350-ffd6e800-79e4-11ea-83ed-62b37c63dafc.png)

![image](https://user-images.githubusercontent.com/3603130/78850364-09605000-79e5-11ea-946e-28c5df5e3e71.png)

**Comment by sradu** [comment]
Love this. @lisamai can you please style that select with default tailwind. I believe the classes are in the project sort, you can just copy and paste those should be the defaults.

**Comment by lisamai** [comment]
Good call, thanks @sradu! Updated the style and element structure so it's consistent with status.

![image](https://user-images.githubusercontent.com/3603130/78855752-cf964600-79f2-11ea-95b6-89213bccf4b7.png)
